name: Run tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.1
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.1"
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y poppler-utils tesseract-ocr
    - name: Install Poetry
      run: |
        python -m pip install poetry
    - name: Configure poetry
      run: |
        python -m poetry config virtualenvs.in-project true
    - name: Cache the virtualenv
      uses: actions/cache@v2
      with:
        path: ./.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      run: |
        python -m poetry install
    - name: Test with pytest
      env:
        HUGGINGFACEHUB_API_KEY: ${{ secrets.HUGGINGFACEHUB_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        VOYAGE_API_KEY: ${{ secrets.VOYAGE_API_KEY }}
        COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        UNSTRUCTURED_API_KEY: ${{ secrets.UNSTRUCTURED_API_KEY }}
        UNSTRUCTURED_API_URL: ${{ secrets.UNSTRUCTURED_API_URL }}
      run: |
        cd ./tests
        python -m poetry run pytest -s -v